### ISSUE TITLE
Add `Queue` as a foundational primitive

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#212]
We have channels which are basically an ephemeral message bus, but what we're lacking right now is a persistent queue. This would be somewhat similar to `Mailbox` in bigtest, but with a slimmed down and simplified API.

**Comment by jnicklas** [comment]
It could be used to replace the semaphore in the implementation of channels, I think?

**Comment by cowboyd** [comment]
> t could be used to replace the semaphore in the implementation of channels, I think?

Do you mean `createSubscription`? Probably

I also think we need something like a Mailbox externally too which is itself subscribable, that way you can attach a queue to a subscription and have it start collecting results before you are ready to consume them. This feels especially important when you are passing something to a "handler" operation where you cannot guarantee what happens between invoking the handler operation and when that handler starts consuming the subscription.

**Comment by jnicklas** [comment]
I'm sort of coming around to mailboxes being kind of good.

I know … coming full circle 🤷‍♂️

When I was writing https://github.com/thefrontside/bigtest/pull/665, I ran into this where replacing the mailboxes with channels actually started introducing a bunch of race-conditions. The fact that mailboxes preserve the messages in the queue was kind of a key design consideration that we lost along the way.

I'm thinking that both mailboxes and channels have their place, but we need to sort out our terminology and when to use which.

**Comment by cowboyd** [comment]
I agree, but I think where we're better positioned is that subscription is the primitive and with that in hand, you can build a "Buffer" or "Mailbox" or "Queue" class that lets you create a stateful subscribable off of a stateless subscribable. That way, if you want to have guaranteed delivery of the same source to _two_ consumers, you can use a single channel, but two buffers so that the consumers won't "steal" messages from each other because they'll each have their own buffer over the single source.

```ts
class Buffer<T> implements Subscribable<T> {
  contents: T[] = [];
  signals: Array<() =>()>;

  static *create(source: Subscribable<T>) {
    let buffer = new Buffer<T>();
    return resource(buffer, subscribe(source).forEach(function*(item) {
      push(buffer, item);
    });
  }

  [SymbolSubscribable]() {
    return createSubscription(function*(publish) {
      while (true) {
        let item = this.contents.shift();
        if (item) {
          publish(item);
        } else {
          let { resolve, promise } = Deferred();
          this.signals.push(resolve);
          yield promise;
        }
      }
    });
  } 
}

function push<T>(buffer: Buffer<T>, item: T) {
  buffer.contents.push(item);
  let { signals } = this;
  this.signals = [];
  for (let signal of signals) {
    signal();
  }
}
```

We can begin to get fancy too by passing parameters to a buffer about how many messages it may store, what to do when overflow occurs (error, drop latest, drop first) etc...

Now a buffer is 100% usable by all our other consumer/subscriber code because it implements the `Subscribable` interface and can be handed out where appropriate.
