### ISSUE TITLE
What should happen when a controller throws during halt caused by an error?

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#349]
I ran into this edge case, where I am unsure of what the correct behaviour is:

``` typescript
run(function*(inner) {
  inner.spawn(function* willBoom() {
    yield sleep(5);
    throw new Error('boom');
  });
  try {
    yield
  } finally {
    throw new Error('bang');
  }
});
```

Obviously this is going to reject, but the question is *which error* is it going to reject with? The `boom` error is the original error and therefore maybe should have preference, on the other hand the `bang` error thrown in the controller is "closer" to the task, and therefore an argument could be made that that is the error that should be thrown.

**Comment by jnicklas** [comment]
@cowboyd would love to hear your opinion on this.

**Comment by jnicklas** [comment]
Maybe this should even be its own very special case, with some kind of composite error which shows *both*?

**Comment by cowboyd** [comment]
>Maybe this should even be its own very special case, with some kind of composite error which shows both?

That seems really reasonable especially because this represents what is almost certainly an internally inconsistent state and you want to discourage anybody from recovering from this error. For example, if your body throws a `FetchError` which you have a catch block for because it is a condition for which you have retry logic, then you don't want the `FetchError` to "win", so that seems to rule that out.

My gut tells me that either the `finally` error should win or that we use a composite. The form might be simpler to implement, but even so, we can't _not_ detect the situation because at the very least we need to issue some sort of warning about "hey, this exception was hidden because of an error in your teardown. Uncaught teardown errors should probably be a warning as well even if they don't occur just after a process error.

**Comment by jnicklas** [comment]
I just looked into this, and it's very, very tricky to implement correctly, which leads me to think that it's probably not worth it. I think the added complexity is not justified for this.

**Comment by cowboyd** [comment]
I'm ok punting on this one 👍🏻
