### ISSUE TITLE
How do you recover from errors in resources?

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/effection#493]
We run into this situation in simulacrum where we are starting multiple servers, and allowing the port to be configured, but if multiple processes select the same port, then the server resource fails, and there isn't a really good way to recover from it, so the entire server ends up crashing.

How would you even recover from this? I can think of a couple of options. One way would be to have some operation that funnelled (and allowed you to catch) all errors coming to a task from itself:

```js
import { run, self } from 'effection';

run(function*() {
  yield createResourceOne();
  yield createResourceTwo();
  
  try {  
    yield self;
  } catch (error) {
    console.log('error occured');
  }
});

```

Another might be to establish a "trap" for specific tasks:

``` javascript
import { run, trap } from 'effectcion'

run(function*() {
  let one = yield createResourceOne();
  let two = yield createResourceTwo();

  try {
    yield trap(one, two);
  } catch (error) {
    console.log('error occured');
  }
});
```

That would allow handling specific errors from one resource but not the other by just not saying that you want to trap it.

**Comment by jnicklas** [comment]
I think this is a very tricky problem.

It's worth noting that there is a current solution to this, which I would call something like a task-error-boundary. Basically, wrapping resources (or other operations) in a task creates an error boundary, allowing errors to be brought from the background to the foreground. In your example, it would look something like this:

``` typescript
import { run } from 'effectcion'

run(function*() {
  try {
    yield function*() {
      let one = yield createResourceOne();
      let two = yield createResourceTwo();
      // more stuff here
    }
  } catch (error) {
    console.log('error occured');
  }
});
```

I think it should be fairly clear why and how this works: the operation we're yielding to inside of the try blocks basically creates a boundary, and any error thrown inside of it, even one thrown from a resource, will bubble up and be caught in the `catch` block. So while this pattern is pretty self-explanatory once you see it, actually coming up with this as a solution to the problem is very much not obvious.

So there are basically two solutions to this:

1. Documenting this pattern better
2. Making this pattern more ergonomic

The former is a no-brainer, the latter might be similar to something like `ensure`, where we're taking a pattern and encapsulating it in some kind of higher-level operation, maybe something like `trap` though I'm not entirely sure how this would work.

# Alternatives

## yield self

I think this pattern looks elegant, but I'm not sure how it'd work in practice. Basically when a child becomes trapped it now needs to be aware that there is a self-trapper somewhere and redirect the error to that place instead. I feel that the implementation of this would be complex and prone to race conditions.

## trap resource

This basically would detach the resource from its context, and move it to a different spot in the task tree, something I'm reluctant about doing. It opens up questions what happens if the resource crashes before the `trap` is hit and so on, I think the `yield self` solution is more promising than this.

## Supervisors

This is something we've known about for a while, but that might be relevant here. A common use case for error recovery is being able to restart a task when some failure occurs. This is where supervisors come in. Basically a supervisor would handle any crash and restart the subcomponent on failure. This doesn't solve all cases where this problem occurs, but maybe the most common ones?

**Comment by cowboyd** [comment]
🤦🏻 Of course! 

I think that documenting the error boundary is a great solution in that it requires **zero** extra implementation. I was even aware of this pattern, but it was not obvious how to embed it into simulacrum.

As for supervisors, I _think_ that we can implement supervisors at the library level without the need for extending the runtime. For example, here is a naïve implementation of Erlang's [`one_for_all`][1] restart strategy that restarts an entire group of operations if any one of them fails (for simplicity, there is no restart intensity).

```ts
function* oneForAll(...operations: Operation<unknown>[]): Operation<void> {
    restart:
    try {
      yield function* errorBoundary() {
        for (let operation of operations) {
          yield spawn(operation);
        }
        yield;
      }
     } catch (error) {
       console.error(error);
       break restart;
    }
}
```

[1]: https://erlang.org/doc/man/supervisor.html
