### ISSUE TITLE
Ergonomic way of creating a resolved/rejected future

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#495]
Sometimes we want to "lift" a value into being a future. For promises, there is `Promise.resolve(123)` for this purpose. We should add a similar API for futures.

But what would this API look like? Some bike-sheddable alternatives:

- `Future.resolve(123)`
- `resolvedFuture(123)`
- `createResolvedFuture(123)`
- ???

**Comment by cowboyd** [comment]
The order in which you've listed them is the order of my personal preference. I don't particularly like APIs that are coupled to a  an object that just holds functions, but that is the convention with `Promise` and `Promise.{resolve, reject}` and since we're pulling up our API as a 1:1 replacement for `Promise`, `async/await`, any ways we can retain parallels will bind that association in people's minds tighter.
