### ISSUE TITLE
Link API documentation

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#501]
I think the API documentation is getting published now, but it is not linked from the website. Clicking on `API Reference` is a dead link. I'm not entirely sure how this is supposed to be fixed.

**Comment by minkimcello** [comment]
It is broken at the moment because netlify doesn't allow double redirects

But if you get redirected _from_ effection's netlify site, it will get you to the api docs

https://effection.netlify.app/effection/docs/guides/introduction

<blockquote><img src="https://frontside.com/effection/images/meta-image.png" width="48" align="right"><div><strong><a href="https://frontside.com/effection/docs/guides/introduction">Introduction | Effection</a></strong></div><div>Effection is a framework for Node and the browser that makes building</div></blockquote>

**Comment by cowboyd** [comment]
Any ideas on how to fix this?

**Comment by minkimcello** [comment]
we could try to set the redirect for the api on frontside.com repo instead of effection

**Comment by minkimcello** [comment]
@cowboyd I'm talking to @jorgelainfiesta about how we can fix this. I had [this](https://github.com/thefrontside/frontside.com/pull/147) PR created but it looks like we need to fiddle with the configs on the effection website a bit to complete the fix?

**Comment by minkimcello** [comment]
https://frontside.com/effection/docs/guides/introduction

if you click `API` from that link, you'll see this has been fixed. looks like the styling still needs to be tweaked

<blockquote><img src="https://frontside.com/effection/images/meta-image.png" width="48" align="right"><div><strong><a href="https://frontside.com/effection/docs/guides/introduction">Introduction | Effection</a></strong></div><div>Effection is a framework for Node and the browser that makes building</div></blockquote>

**Comment by minkimcello** [comment]
Closing because it's been fixed via #504 and #505
