### ISSUE TITLE
How production-ready Effection is?

### ISSUE THREAD

**Issue by shamrin** [thefrontside/effection#654]
Thank you for the great framework! Structured Concurrency is a must for complicated concurrent applications. I had a lot of fun [experimenting with Trio](https://github.com/shamrin/sitewatch/blob/main/sitewatch/__init__.py) in the past.

How production-ready do you consider Effection to be? Specifically:

1. What kind of apps it was tested on?
2. What are the known limitations and drawbacks?
3. What is the performance penalty for using Effection compared to `async`/`await`?

I've read the manual, but unfortunately I didn't find the answers to these questions.

**Comment by cowboyd** [comment]
Hi there @shamrin! We agree, and can measure time in the era before and after we discovered structured concurrency. 

> What kind of apps it was tested on?

We consider Effection to be production ready for our applications. We originally developed it for writing [BigTest](https://frontside.com/bigtest) (I don't see how it would have been possible without it), and then we migrated [Interactors](https://frontside.com/interactors) over to use it in order to support cancelling interactions. We've also used it quite extensively on internal client projects, especially in the area of testing multi-process systems because we can manage processes quite effectively with it. In the area of process management it is particuaraly useful since adding an implicit lifetime to external process is really helpful. To that end, I believe it is used in [covector](https://github.com/jbolda/covector). 

> What are the known limitations and drawbacks?

For me personally, the biggest drawback is that using it with TypeScript is sub-optimal. [There are workarounds](https://frontside.com/effection/docs/guides/typescript), but it is still annoying at times. For others, I think there is a definitely a learning curve you need to surmount to think in terms of resources and operations and generators "feel scary".

> What is the performance penalty for using Effection compared to async/await?

I do not have any data on this other than it has never felt any slower. One thing that is interesting about Effection that sets it apart from `async/await` is that whenever operations _can_ resolve synchronously, they _will_ resolve synchronously, and so theoretically it has a higher upper limit than async / await in which every promise in the chain must resolve in a separate tick of the run loop.

**Comment by cowboyd** [comment]
I'm going to marked this as answered. Let me know if you have any other questions, or feel free to stop by our [discord](https://discord.gg/r6AvtnU)
