### ISSUE TITLE
Exception has occurred: Error: halted

### ISSUE THREAD

**Issue by kovan** [thefrontside/effection#662]
Hi. I am new to Effection. I am trying to port a piece of code from Python to Javascript + Effection.

When running the code Visual Studio Code debugger with the option "Pause on uncaught exceptions", I get a exception that I don't know where it comes from:

> Exception has occurred: Error: halted
>   at /home/k/prj/videosdb/backend/js/node_modules/@effection/core/dist-cjs/future.js:78:28
>     at run (/home/k/prj/videosdb/backend/js/node_modules/@effection/core/dist-cjs/future.js:53:21)
>     at Object.run (/home/k/prj/videosdb/backend/js/node_modules/@effection/core/dist-cjs/run-loop.js:20:29)
>     at consume (/home/k/prj/videosdb/backend/js/node_modules/@effection/core/dist-cjs/future.js:46:17)
>     at /home/k/prj/videosdb/backend/js/node_modules/@effection/core/dist-cjs/future.js:70:13
>     at new Promise (<anonymous>)
>     at getPromise (/home/k/prj/videosdb/backend/js/node_modules/@effection/core/dist-cjs/future.js:69:38)
>     at [continuation].catch (/home/k/prj/videosdb/backend/js/node_modules/@effection/core/dist-cjs/future.js:89:33)
>     at [Task 6].halt (/home/k/prj/videosdb/backend/js/node_modules/@effection/core/dist-cjs/task.js:93:31)
>     at Object.halt (/home/k/prj/videosdb/backend/js/node_modules/@effection/core/dist-cjs/controller/iterator-controller.js:67:28)

The line within Effection that raises the exeption is:
```
                    reject(new halt_error_1.HaltError());
```
I can't say much more. I have no idea of what part of my code is causing this, but I can post parts or all of it on request.

Is this behavior normal?, or am I doing something wrong? how to prevent this?. BTW without enabling  "Pause on uncaught exceptions" on the debugger the program seems to run fine.

Thank you for your time.

**Comment by cowboyd** [comment]
I can answer more on this later, but yes, this is normal behavior. The reason is because Effection Tasks, while not promises themselves can be consumed as promises. If you consume it as a promise, however, we need to let consumers know that a value will never be arriving because it the task was halted. As a result, whenever a Task is halted, its associated Promise is rejected. Again, you only see a HaltError if you are consuming a Task as a promise. E.g.

```ts
let task = run(function*() {
  yield; // just yield forever.
});

task.halt();

await task; //<== throws HaltError
```

It's annoying that the debugger is picking it up, and I think we could perhaps do better and only reject the promise if we know that we have consumers of the promise.

Thanks for reporting this, since it is confusing, and I think that we could make it less so.

**Comment by cowboyd** [comment]
@kovan Would you mind posting your code that is using Effection? Because the promise is only created if someone is calling `then()`, `catch()`, or `finally()` on a `Task`, which means that someone is consuming the task as a promise.

**Comment by kovan** [comment]
Sure, this is the code: 

```javascript 
import { google } from 'googleapis'
import { Firestore } from '@google-cloud/firestore'
import { main, createQueue, spawn, all } from 'effection';
import "path"
import _ from "lodash"




class DB {
    constructor() {
        this.firestore = new Firestore()
    }
    *init() {
        const metaDoc = doc(this.firestore, "meta/meta")
        let snapshot = yield getDoc(metaDoc)
    }
    *get(path, id) {
        docRef = doc(this.firestore, path, id)
        docSnp = yield getDoc(docRef)
        return docSnp.exists ? docSnp : null
    }
}



function* dereferencePages(data, apiMethod, apiParams) {
    while (true) {
        if (!("nextPageToken" in data))
            break
        apiParams.pageToken = response.data.nextPageToken
        response = yield apiMethod(apiParams)
        data = { ...response.data }
    }
}


function* getWithCache(db, apiMethod, apiParams, id) {
    let headers = {}
    let cache = db.firestore.collection("cache")
    let cached_ref = cache.doc("id")
    let cached_doc = yield cached_ref.get()

    if (cached_doc.exists) {
        if (_.get(cached_doc, "videosdb.etag")) {
            headers["If-None-Match"] = cached_doc.videosdb.etag
        }
    }

    apiParams.headers = headers

    let response = yield apiMethod(apiParams)

    let result = null
    switch (response.status) {
        case 304:
            result = {
                doc: cached_doc,
                modified: false
            }
            break
        default:
            let full_data = dereferencePages(response.data, apiMethod, apiParams)
            let doc_ref = cache.doc(id)
            yield doc_ref.set(full_data.items)

            result = {
                doc: full_data,
                modified: true
            }
    }


    return result
}

class PlaylistRetriever {
    constructor(db, api, queue) {
        this.db = db
        this.queue = queue
        this.api = api

    }
    *start() {
        let channel_id = process.env.YOUTUBE_CHANNEL_ID
        let params = {
            "part": "snippet,contentDetails,statistics",
            "id": channel_id
        }
        console.info("Retrieving channel " + channel_id)
        let method = this.api.channels.list.bind(this.api)
        let channel_info = yield getWithCache(this.db,
            method,
            params,
            channel_id)
        console.debug(channel_info)

        this.YT_CHANNEL_NAME = channel_info.snippet.title
        let doc = this.db.firestore.doc("channel_infos/" + channel_id)

        yield doc.set(channel_info, { merge: true })
        let playlist_ids = null
        if (process.env.DEBUG) {
            let params = {
                "part": "contentDetails",
                "channelId": channel_id
            }
            let response = yield this.api.channelSections.list(params)

        }
        let playlistQueue = createQueue("Playlist queue")

    }

}

class Downloader {
    constructor(exclude_transcripts = false) {
        this.valid_video_ids = []
        this.db = new DB()
        this.api = google.youtube({
            version: 'v3',
            auth: process.env.YOUTUBE_API_KEY
        })
    }
    *check_for_new_videos() {
        console.info("Sync start")
        let retriever = new PlaylistRetriever(this.db, this.api)

        yield spawn(retriever.start())
        console.info("Sync finished")
        return true

    }
}



main(function* () {
    console.debug(process.env)
    try {
        let d = new Downloader()
        let result = yield spawn(d.check_for_new_videos())
        console.info("RESULT: " + result)
    } catch (err) {
        console.error("ERROR: " + err)
    }


})
```


And here is the package.json, in case you want to run it:

```json
{
    "name": "backend",
    "version": "1.0.0",
    "main": "index.js",
    "license": "MIT",
    "private": true,
    "dependencies": {
        "@google-cloud/firestore": "^6.0.0",
        "effection": "^2.0.4",
        "googleapis": "^107.0.0",
        "lodash": "^4.17.21",
        "slugify": "^1.6.5"
    },
    "type": "module",
    "scripts": {
        "start": "node app.js"
    }
}
```

**Comment by cowboyd** [comment]
@kowan One thing I noted is that in most cases, you do not need to call `spawn()`. `spawn()` should only be used for code that you want to run _asynchronously_. For example, the code where you get your result:

```js
let result = yield spawn(d.check_for_new_videos());
```

`result` is `Task` that will eventually return the result you want. In order to get the actual result from the task, you would say:

```js
let resultTask = yield spawn(d.check_for_new_videos());
let result = yield resultTask;
```

However, you can just skip the spawn and access the result of the `check_for_new_videos()` operation directly.

```js
let result = yield d.check_for_new_videos()
```

Does that make sense? I've created a gist out of your files so that we can have a common place to talk about it. Have a look: https://gist.github.com/cowboyd/a13897e6f8dbffbfb75bdd6a2a4b1eac

Also, feel free to drop by on Discord https://discord.gg/r6AvtnU

<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> Gist</div><div><strong><a href="https://gist.github.com/cowboyd/a13897e6f8dbffbfb75bdd6a2a4b1eac">Example from https://github.com/thefrontside/effection/issues/662#issuecomment-1243863041</a></strong></div><div>Example from https://github.com/thefrontside/effection/issues/662#issuecomment-1243863041 - main.mjs</div></blockquote>
<blockquote><img src="https://cdn.discordapp.com/icons/700803887132704931/2705cb99fc37201f48b07a20840cc73e.jpg?size=256" width="48" align="right"><div><img src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/invite/r6AvtnU">Join the Frontside Discord Server!</a></strong></div><div>Check out the Frontside community on Discord - hang out with 193 other members and enjoy free voice and text chat.</div></blockquote>

**Comment by kovan** [comment]
Now it doesn't happen anymore. Also, I was wondering how to wait for the spawn() calls. So two issues solved at once! thank you.

As we said the behavior is a bit(a lot) obscure, but now it works for me and I understand why, so I'm happy.

See ya!
