### ISSUE TITLE
Should spawn create a child in the parent?

### ISSUE THREAD

**Issue by jnicklas** [thefrontside/effection#76]
When we are inside an operation, and we have received a `Controls`, then we have the ability to `spawn` a new context, this context is currently a child of the current operation, however I don't think this is ever what we want. In almost all cases, we actually want the spawned context to be a *sibling* of the current operation. This seems a bit a bit counterintuitive at first, but it makes sense if we look at it as suspending something into the background. If the spawned context is a child of the current operation, then it can't ever outlive it.

It's worth noting that we've done various weird workarounds in a lot of places to actually spawn a sibling instead. For example in [Effection's own fork implementation](https://github.com/thefrontside/effection.js/blob/2140cb944c640021f1e04c614312cdfe107d88d4/src/control.js#L115) and [in `watch` in bigtest server](https://github.com/bigtestjs/server/blob/4d12c0c11a31d75c3bdb21b7f7aafcb98b915bdf/src/effection/events/mailbox.ts#L46).

Here is some example code illustrating this point:

``` typescript
import { Controller, monitor, main } from 'effection';


function createChild() {
  return ({ resume, spawn }) => {
    let runChild: Controller = ({ ensure }) => {
      console.log("starting child");
      ensure(() => {
        console.log("finishing child");
      });
    };
    resume(spawn(monitor(runChild)));
  }
}

main(function*() {
  console.log("starting main");

  yield createChild();

  console.log("finishing main");
});
```

This currently prints:

```
starting main
starting child
finishing child
finishing main
```

Since the child is immediately killed after being spawned. But we really want the child to outlive the yield point and to only be killed at the end of main.

It's interesting to note that this combination also solves our desire to do RAII-like patterns, without actually having to expose the parent. Just spawning a monitor in the parent will tie the resulting resource to the lifetime of the parent. No need to be able to even *see* the parent context.

**Comment by jnicklas** [comment]
Maybe it would actually be sensible to have two separate methods, `spawnChild` and `spawnSibling`? At the moment I can't really come up with a use-case for spawning a child though.

**Comment by cowboyd** [comment]
The only place I can see that you want to spawn in the current context is if your operation is serving in a supervisory role. So for example, if you have one operation that manages 10 operations, restarting them at appropriate times, then you want to be spawning children, but for most "atomic" operations what you really want, as you say, is to be spawning siblings.

An example of spawning children, not siblings, in the current codebase is in the implementation for the `Generator` control function which makes sense since it is a supervisory operation.

For now, I think having `spawn` create a sibling makes sense, and then having a separate method `spawnChild` or even `newContext`. However, something about this tickles me as being similar to solving the "rightward drift" problem of moving down a tree, and while still fuzzy in my head, I wonder if  perhaps their is a similar solution of "returning the next promise" as a way for an operation to participate in the level above it.

promise:

```ts
await $.ajax.get('/jwt/token')
  .then(token => {
    return $.ajax.post('/signed-upload-urls/')
  })
  .then(({ url }) => {
    return $ajax.put(url, imageData);
  });
```

By returning a promise each time, that promise is executed in the context level above it rather than creating a new one.

I wonder if there is a shared solution here of perhaps returning a new operation from the control function (instead of void), then that operation is run in the parent context.

`type Controller = Controls => (Operation | void)`

**Comment by cowboyd** [comment]
If we do make `spawn` operate on the parent, then we also need to somehow make the parent `resume` and `fail` functions available from the spawn so that you can link the new sibling back to the parent.

**Comment by jnicklas** [comment]
I think that our interface to the parent should be pretty limited. Being able to call `resume` on the parent seems dangerous. A child should be able to bubble up an error to its parent, but not change its return value, imo. Then we'd be sort of back to the behaviour of 0.4 where any child could randomly resume its parent, which I don't think is good.

**Comment by jnicklas** [comment]
With the advent of context returns and resources, this is no longer relevant.
