### ISSUE TITLE
Doesn't work with node event

### ISSUE THREAD

**Issue by geohuz** [thefrontside/effection#924]
I have the following code: 

```js
import { EventEmitter } from "events";
import { main, on, each } from "effection";

const localEvent = new EventEmitter();
await main(function* () {
  for (let value of yield* each(on(localEvent, "go"))) {
    console.log("get event: ", value);
    yield* each.next();
  }
});

localEvent.emit("go", "hello");
```

It throws `TypeError: target.addEventListener is not a function`, So I'm assuming we don't need this structure in the nodejs event?

**Comment by cowboyd** [comment]
The first reason why it does not work is that Effection only comes bundled with standard APIs, and Node's `EventEmitter` class is not a standard API.  To use vanilla Effection, you would have to use the [`EventTarget`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget) which is available in Node as well as in browsers.

Here is your example updated work with `EventTarget`

```js
import { main, on, each, spawn, sleep } from "effection";

const localEvent = new EventTarget();
await main(function* () {

  yield* spawn(function*() {
    while (true) {
      yield* sleep(1000);
      localEvent.dispatchEvent(new CustomEvent("go", { detail: "hello" }));
    }
  })

  for (let value of yield* each(on(localEvent, "go"))) {
    console.log("get event: ", value);
    yield* each.next();
  }
});
```

Notice that I had to move the dispatch of the event into a background task. This is because you don't actually ever move past the `await main()` which encompasses the entire run of your program. I moved it into the background and made it periodic to demonstrate it dispatching over the course of time.

All that said, you can use the `EventEmitter` class, but you will need to make the stream for it by hand. To do this, I would recommend a simple resource that provides a queue with all the elements.

```ts
import { createQueue } from "effection";
/**
* Create a `Stream` out of any Node event emitter
*/
export function onEmit(emitter: EventEmitter, eventName: string): Stream<string, never> {
  return resource(function*(provide) {
    let queue = createQueue<string, never>();

    try {
      emitter.on(eventName, queue.add);
      yield* provide(queue);
    } finally {
      emitter.off(eventName, queue.add);
    }
  });
}
```

Then, you can use to loop as before:

```ts
import { EventEmitter } from "events";
import { main, each, Stream, resource, createQueue, spawn, sleep } from "effection";
import { onEmit } from "./on-emit.ts";

const localEvent = new EventEmitter();

await main(function* () {

  yield* spawn(function*() {
    while (true) {
      yield* sleep(1000);
      localEvent.emit("go", "hello");
    }
  })
  
  for (let value of yield* each(onEmit(localEvent, "go"))) {
    console.log("get event: ", value);
    yield* each.next();
  }
});
```

Hope that helps!

**Comment by geohuz** [comment]
@cowboyd  Thanks for the detail explainatio!  I learned a lot from this reply!

**Comment by geohuz** [comment]
BTW, I wrote another version which moves out the dispatcher and logic so I can organize my program better, pls let me know if this is appropriate:

```js
import { main, sleep, spawn, on, each } from "effection";

const localEvent = new EventTarget();
await main(function* () {
  let dispatcher = yield* spawn(emitter);
  let receiver = yield* spawn(eventReceiver);

  yield* dispatcher;
  yield* receiver;
});

function* emitter() {
  while (true) {
    yield* sleep(1000);
    localEvent.dispatchEvent(new CustomEvent("go"), "hello");
  }
}

function* eventReceiver() {
  for (let value of yield* each(on(localEvent, "go"))) {
    console.log("get event: ", value);
    yield* each.next();
  }
}
```

**Comment by cowboyd** [comment]
Yes, that is good. Although it could be simplified further. Because both `dispatcher` and `receiver` will loop forever, you could also just suspend the main task. That way, you don't need to capture them as references.

```ts
await main(function* () {
  yield* spawn(emitter);
  yield* spawn(eventReceiver);

  yield* suspend();
});
```

But that is mainly stylistic. It's up to you!
